
// get student data action type
export const GET_STUDENT_PENDING = "GET_STUDENT_PENDING";
export const GET_STUDENT_FULLFILLED = "GET_STUDENT_FULLFILLED";
export const GET_STUDENT_REJECTED = "GET_STUDENT_REJECTED";

// post student data action type ;
export const CREATE_STUDENT_PENDING = "CREATE_STUDENT_PENDING";
export const CREATE_STUDENT_FULLFILLED = "CREATE_STUDENT_FULLFILLED";
export const CREATE_STUDENT_REJECTED = "CREATE_STUDENT_REJECTED";



