
const day = Array.from({length: 31}, (_,i) =>{
    return(31 -i);
});

export const days = day.reverse();


export const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
  ];


// Create a array for the the year

const year = Array.from({length: new Date().getFullYear() - 1899}, (_, i) =>{
    return(new Date().getFullYear() - i);
})


export const years = year.reverse();


// Create all Distric array ;
export const  districs = [
    "Dhaka",
    "Chittagong",
    "Rajshahi",
    "Khulna",
    "Barisal",
    "Sylhet",
    "Rangpur",
    "Mymensingh",
    "Cox's Bazar",
    "Jessore",
    "Comilla",
    "Narayanganj",
    "Bogra",
    "Dinajpur",
    "Feni",
    "Pabna",
    "Tangail",
    "Jamalpur",
    "Narsingdi",
    "Bagerhat",
    "Natore",
    "Joypurhat",
    "Kushtia",
    "Manikganj",
    "Noakhali",
    "Brahmanbaria",
    "Sherpur",
    "Satkhira",
    "Faridpur",
    "Magura",
    "Moulvibazar",
    "Narail",
    "Munshiganj",
    "Gazipur",
    "Kishoreganj",
    "Lakshmipur",
    "Kurigram",
    "Meherpur",
    "Chapainawabganj",
    "Netrakona",
    "Shariatpur",
    "Bhola",
    "Jhenaidah",
    "Chuadanga",
    "Lalmonirhat",
    "Satkhira",
    "Panchagarh",
    "Thakurgaon",
    "Habiganj",
    "Sirajganj",
    "Jhalokathi",
    "Patuakhali",
    "Chandpur",
    "Madaripur",
    "Gaibandha",
    "Chapai Nawabganj",
    "Sunamganj",
    "Bandarban",
    "Narail",
    "Shariatpur",
    "Khagrachari",
    "Rangamati",
    "Lakshmipur",
    "Magura",
    "Moulvibazar",
    "Pirojpur",
    "Nagarpur",
    "Laxmipur",
    "Jhenaidah",
    "Kushtia",
    "Mymensingh",
    "Netrokona",
    "Nilphamari",
    "Barguna",
    "Bhola",
    "Panchagarh",
    "Patuakhali",
    "Pirojpur",
    "Sherpur",
    "Sunamganj",
    "Tangail",
    "Thakurgaon",
    "Bandarban",
    "Barguna",
    "Bogra",
    "Chandpur",
    "Chapai Nawabganj",
    "Chuadanga",
    "Comilla",
    "Cox's Bazar",
    "Dhaka",
    "Dinajpur",
    "Faridpur",
    "Feni",
    "Gaibandha",
    "Gazipur",
    "Habiganj",
    "Jamalpur",
    "Jhalokathi",
    "Joypurhat",
    "Khagrachari",
    "Khulna",
    "Kishoreganj",
    "Kurigram",
    "Kushtia",
    "Lakshmipur",
    "Lalmonirhat",
    "Magura",
    "Manikganj",
    "Meherpur",
    "Moulvibazar",
    "Munshiganj",
    "Mymensingh",
    "Narail",
    "Narayanganj",
    "Narsingdi",
    "Natore",
    "Nawabganj",
    "Netrokona",
    "Nilphamari",
    "Noakhali",
    "Pabna",
    "Panchagarh",
    "Patuakhali",
    "Pirojpur",
    "Rajshahi",
    "Rangamati",
    "Rangpur",
    "Satkhira",
    "Shariatpur",
    "Sherpur",
    "Sirajganj",
    "Sunamganj",
    "Sylhet",
    "Tangail",
    "Thakurgaon"
  ];
  



